### ISSUE TITLE
nest variables inside of objects

### ISSUE THREAD

**Issue by jasonswearingen** [aljazsim/vs-code-typescript-code-explorer#1]
using VSCode June 2018.

if I have code like this:
```typescript
type IUser{
 name:string,
 age:number,
}
```

the code explorer currently lists the properties (name and age) but doesn't list the containing type (IUser).       it would be great if the IUser type was shown and it's containing types were nested.

**Comment by aljazsim** [comment]
Hi Jason.

Please update the extension to the latest version and let me know if it works as expected.
