### ISSUE TITLE
Doesn't work in latest VS Code release

### ISSUE THREAD

**Issue by ghost** [aljazsim/vs-code-typescript-code-explorer#2]
Doesn't work in this configuration.  Code Explorer window opens and displays "no elements found".

Version: 1.30.1 (system setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

**Comment by uglycoyote** [comment]
I second this.  When first installed it said "no data provider found" (this was when I invoked it by clicking on the {} icon on the left.  Then I tried following the instructions and opening it through the "Show Code Explorer" action, which led me to the blank list saying "no elements found"

**Comment by aljazsim** [comment]
I've just released a new version with heaps of fixes and new features. Please update the extension and give it another try.
